apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    app: voting-app
    name: result-deployment

spec:
  template:
    metadata:
      name: result-pod
      labels:
        app: voting-app
        name: result-pod
    spec:
      containers:
      - name: result
        image: dockersamples/examplevotingapp_result
        ports:
        - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: voting-app
      name: result-pod
