apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deployment
  labels:
    app: voting-app
    name: voting-deployment

spec:
  template:
    metadata:
      name: voting-pod
      labels:
        app: voting-app
        name: voting-pod
    spec:
      containers:
      - name: voting
        image: dockersamples/examplevotingapp_vote
        ports:
        - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: voting-app
      name: voting-pod
