apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: voting-app
    name: worker-deployment

spec:
  template:
    metadata:
      name: worker-pod
      labels:
        app: voting-app
        name: worker-pod
    spec:
      containers:
      - name: worker
        image: dockersamples/examplevotingapp_worker
  replicas: 3
  selector:
    matchLabels:
      app: voting-app
      name: worker-pod
