apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    name: db-service
    app: voting-app

spec:
  type: ClusterIP
  ports:
  - targetPort: 5432
    port: 5432
  selector:
    app: voting-app
    name: db-pod

