apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    name: postgres-service
    app: voting-app

spec:
  type: ClusterIP
  ports:
  - targetPort: 5432
    port: 5432
  selector:
    app: voting-app
    name: postgres-pod