apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: voting-app

spec:
  type: ClusterIP
  ports:
  - targetPort: 6379
    port: 6379
  selector:
    app: voting-app
    name: redis-pod

