apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    name: result-service
    app: voting-app

spec:
  type: LoadBalancer
  ports:
  - targetPort: 80
    port: 80
  selector:
    app: voting-app
    name: result-pod

